// <auto-generated />
using System;
using Flight_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Flight_Project.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.AircraftDB", b =>
                {
                    b.Property<int>("AircraftDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AircraftDBId");

                    b.ToTable("AircraftTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.AircraftsDB", b =>
                {
                    b.Property<int>("AircraftsDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DictionariesDBId")
                        .HasColumnType("int");

                    b.HasKey("AircraftsDBId");

                    b.HasIndex("DictionariesDBId");

                    b.ToTable("AircraftsDB");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.ArrivalDB", b =>
                {
                    b.Property<int>("ArrivalDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("at")
                        .HasColumnType("datetime2");

                    b.Property<string>("iataCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("terminal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArrivalDBId");

                    b.ToTable("ArrivalTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.CarriersDB", b =>
                {
                    b.Property<int>("CarriersDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DictionariesDBId")
                        .HasColumnType("int");

                    b.HasKey("CarriersDBId");

                    b.HasIndex("DictionariesDBId");

                    b.ToTable("CarriersDB");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.CurenciesDB", b =>
                {
                    b.Property<int>("CurenciesDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DictionariesDBId")
                        .HasColumnType("int");

                    b.HasKey("CurenciesDBId");

                    b.HasIndex("DictionariesDBId");

                    b.ToTable("CurenciesDB");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.DatumDB", b =>
                {
                    b.Property<int>("DatumDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FlightOffersSearchDBId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceDBId")
                        .HasColumnType("int");

                    b.Property<int?>("PricingOptionsDBId")
                        .HasColumnType("int");

                    b.Property<string>("id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("instantTicketingRequired")
                        .HasColumnType("bit");

                    b.Property<string>("lastTicketingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("nonHomogeneous")
                        .HasColumnType("bit");

                    b.Property<int>("numberOfBookableSeats")
                        .HasColumnType("int");

                    b.Property<bool>("oneWay")
                        .HasColumnType("bit");

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("validatingAirlineCodes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DatumDBId");

                    b.HasIndex("FlightOffersSearchDBId");

                    b.HasIndex("PriceDBId");

                    b.HasIndex("PricingOptionsDBId");

                    b.ToTable("DataTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.DepartureDB", b =>
                {
                    b.Property<int>("DepartureDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("at")
                        .HasColumnType("datetime2");

                    b.Property<string>("iataCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("terminal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartureDBId");

                    b.ToTable("DepartureTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.DictionariesDB", b =>
                {
                    b.Property<int>("DictionariesDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DictionariesDBId");

                    b.ToTable("DictionariesTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.FareDetailsBySegmentDB", b =>
                {
                    b.Property<int>("FareDetailsBySegmentDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IncludedCheckedBagsDBId")
                        .HasColumnType("int");

                    b.Property<int?>("TravelerPricingDBId")
                        .HasColumnType("int");

                    b.Property<string>("cabin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fareBasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segmentId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FareDetailsBySegmentDBId");

                    b.HasIndex("IncludedCheckedBagsDBId");

                    b.HasIndex("TravelerPricingDBId");

                    b.ToTable("FareDetailsBySegment");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.FeeDB", b =>
                {
                    b.Property<int>("FeeDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PriceDBId")
                        .HasColumnType("int");

                    b.Property<string>("amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeeDBId");

                    b.HasIndex("PriceDBId");

                    b.ToTable("FeeTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.FlightOffersSearchDB", b =>
                {
                    b.Property<int>("FlightOffersSearchDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DictionariesDBId")
                        .HasColumnType("int");

                    b.Property<int?>("MetaDBId")
                        .HasColumnType("int");

                    b.HasKey("FlightOffersSearchDBId");

                    b.HasIndex("DictionariesDBId");

                    b.HasIndex("MetaDBId");

                    b.ToTable("FlightresultsTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.IncludedCheckedBagsDB", b =>
                {
                    b.Property<int>("IncludedCheckedBagsDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.Property<string>("weightUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncludedCheckedBagsDBId");

                    b.ToTable("IncludedCheckedBagsTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.ItineraryDB", b =>
                {
                    b.Property<int>("ItineraryDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DatumDBId")
                        .HasColumnType("int");

                    b.Property<string>("duration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItineraryDBId");

                    b.HasIndex("DatumDBId");

                    b.ToTable("ItineraryTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.LinksDB", b =>
                {
                    b.Property<int>("LinksDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("self")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinksDBId");

                    b.ToTable("LinksTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.MetaDB", b =>
                {
                    b.Property<int>("MetaDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LinksId")
                        .HasColumnType("int");

                    b.Property<int>("count")
                        .HasColumnType("int");

                    b.HasKey("MetaDBId");

                    b.HasIndex("LinksId");

                    b.ToTable("MetaTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.OperatingDB", b =>
                {
                    b.Property<int>("OperatingDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("carrierCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperatingDBId");

                    b.ToTable("OperatingDB");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.PriceDB", b =>
                {
                    b.Property<int>("PriceDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("base")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grandTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PriceDBId");

                    b.ToTable("PriceTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.PricingOptionsDB", b =>
                {
                    b.Property<int>("PricingOptionsDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fareType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("includedCheckedBagsOnly")
                        .HasColumnType("bit");

                    b.HasKey("PricingOptionsDBId");

                    b.ToTable("PricingOptionsTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.SegmentDB", b =>
                {
                    b.Property<int>("SegmentDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AircraftDBId")
                        .HasColumnType("int");

                    b.Property<int?>("ArrivalDBId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartureDBId")
                        .HasColumnType("int");

                    b.Property<int?>("ItineraryDBId")
                        .HasColumnType("int");

                    b.Property<int?>("OperatingDBId")
                        .HasColumnType("int");

                    b.Property<bool>("blacklistedInEU")
                        .HasColumnType("bit");

                    b.Property<string>("carrierCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfStops")
                        .HasColumnType("int");

                    b.HasKey("SegmentDBId");

                    b.HasIndex("AircraftDBId");

                    b.HasIndex("ArrivalDBId");

                    b.HasIndex("DepartureDBId");

                    b.HasIndex("ItineraryDBId");

                    b.HasIndex("OperatingDBId");

                    b.ToTable("SegmentTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.TravelPriceDB", b =>
                {
                    b.Property<int>("TravelPriceDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("base")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("total")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TravelPriceDBId");

                    b.ToTable("OccupentPriceTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.TravelerPricingDB", b =>
                {
                    b.Property<int>("TravelerPricingDBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DatumDBId")
                        .HasColumnType("int");

                    b.Property<string>("fareOption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("priceTravelPriceDBId")
                        .HasColumnType("int");

                    b.Property<string>("travelerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("travelerType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TravelerPricingDBId");

                    b.HasIndex("DatumDBId");

                    b.HasIndex("priceTravelPriceDBId");

                    b.ToTable("TravelerPricingTbl");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.Search.Links", b =>
                {
                    b.Property<int>("LinksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("self")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinksId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.AircraftsDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.DictionariesDB", null)
                        .WithMany("Aircraft")
                        .HasForeignKey("DictionariesDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.CarriersDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.DictionariesDB", null)
                        .WithMany("Carriers")
                        .HasForeignKey("DictionariesDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.CurenciesDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.DictionariesDB", null)
                        .WithMany("Currencies")
                        .HasForeignKey("DictionariesDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.DatumDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.FlightOffersSearchDB", null)
                        .WithMany("data")
                        .HasForeignKey("FlightOffersSearchDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.PriceDB", "price")
                        .WithMany()
                        .HasForeignKey("PriceDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.PricingOptionsDB", "pricingOptions")
                        .WithMany()
                        .HasForeignKey("PricingOptionsDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.FareDetailsBySegmentDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.IncludedCheckedBagsDB", "includedCheckedBags")
                        .WithMany()
                        .HasForeignKey("IncludedCheckedBagsDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.TravelerPricingDB", null)
                        .WithMany("fareDetailsBySegment")
                        .HasForeignKey("TravelerPricingDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.FeeDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.PriceDB", null)
                        .WithMany("fees")
                        .HasForeignKey("PriceDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.FlightOffersSearchDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.DictionariesDB", "dictionaries")
                        .WithMany()
                        .HasForeignKey("DictionariesDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.MetaDB", "meta")
                        .WithMany()
                        .HasForeignKey("MetaDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.ItineraryDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.DatumDB", null)
                        .WithMany("itineraries")
                        .HasForeignKey("DatumDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.MetaDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.Search.Links", "links")
                        .WithMany()
                        .HasForeignKey("LinksId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.SegmentDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.AircraftDB", "aircraft")
                        .WithMany()
                        .HasForeignKey("AircraftDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.ArrivalDB", "arrival")
                        .WithMany()
                        .HasForeignKey("ArrivalDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.DepartureDB", "departure")
                        .WithMany()
                        .HasForeignKey("DepartureDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.ItineraryDB", null)
                        .WithMany("segments")
                        .HasForeignKey("ItineraryDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.OperatingDB", "operating")
                        .WithMany()
                        .HasForeignKey("OperatingDBId");
                });

            modelBuilder.Entity("Flight_Project.Models.Amadeus.DbMapping.TravelerPricingDB", b =>
                {
                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.DatumDB", null)
                        .WithMany("travelerPricings")
                        .HasForeignKey("DatumDBId");

                    b.HasOne("Flight_Project.Models.Amadeus.DbMapping.TravelPriceDB", "price")
                        .WithMany()
                        .HasForeignKey("priceTravelPriceDBId");
                });
#pragma warning restore 612, 618
        }
    }
}
